import axios from 'axios';

export default async function handler(req, res) {
    const { prompt } = req.query;

    if (!prompt || prompt.trim() === '') {
        return res.status(400).json({ error: 'Prompt is required and cannot be empty.' });
    }

    try {
        const response = await axios.post('https://api.blackbox.ai/api/chat', {
            messages: [{ id: null, content: prompt, role: 'user' }],
            id: null,
            previewToken: null,
            userId: null,
            codeModelMode: true,
            agentMode: {},
            trendingAgentMode: {},
            isMicMode: false,
            isChromeExt: false,
            githubToken: null
        });

        const cleanedResponse = JSON.parse(
            JSON.stringify(response.data).replace(
                /Generated by BLACKBOX\.AI, try unlimited chat https:\/\/www\.blackbox\.ai\\n\\n/g,
                ''
            )
        );

        return res.status(200).json({ result: cleanedResponse });
    } catch (error) {
        console.error('Error fetching response from BlackBox AI:', error);
        return res.status(500).json({ error: 'An error occurred while fetching the response.' });
    }
}
